export const SHEETS_SETTINGS_CSV = "SHEETS_SETTINGS_CSV" as const;
export const SHEETS_BUILDINGS_CSV = "SHEETS_BUILDINGS_CSV" as const;
export const SHEETS_UNIT_TYPES_CSV = "SHEETS_UNIT_TYPES_CSV" as const;
export const SHEETS_UNITS_CSV = "SHEETS_UNITS_CSV" as const;
export const SHEETS_AMENITIES_CSV = "SHEETS_AMENITIES_CSV" as const;
export const SHEETS_POI_CSV = "SHEETS_POI_CSV" as const;
export const SHEETS_DOCUMENTS_CSV = "SHEETS_DOCUMENTS_CSV" as const;
export const SHEETS_PROGRESS_CSV = "SHEETS_PROGRESS_CSV" as const;
export const SHEETS_PAGES_CSV = "SHEETS_PAGES_CSV" as const;

export const REQUIRED_SHEETS_ENV_KEYS = [
  SHEETS_SETTINGS_CSV,
  SHEETS_BUILDINGS_CSV,
  SHEETS_UNIT_TYPES_CSV,
  SHEETS_UNITS_CSV,
  SHEETS_AMENITIES_CSV,
  SHEETS_POI_CSV,
  SHEETS_DOCUMENTS_CSV,
  SHEETS_PROGRESS_CSV,
  SHEETS_PAGES_CSV,
] as const;
